version: '3.7'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - ./credentials:/root/.aws
  
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=060606ijlL
      - POSTGRES_DB=vano_task
    ports:
      - 5432:5432

  nudges:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/usr/src/personalised_nudges
    ports:
      - 8080:80
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: vano@mail.ru
      PGADMIN_DEFAULT_PASSWORD: vanovano
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_data:
  pgadmin_data:
