"""Upgrade database

Revision ID: f6aa008c6268
Revises: 305ff662cec0
Create Date: 2024-03-23 15:21:25.108046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6aa008c6268'
down_revision: Union[str, None] = '305ff662cec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_projects_project_id_fkey', 'users_projects', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_projects_project_id_fkey', 'users_projects', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
