name: Vano Tasks
on:
  push:
    branches:
      - main

jobs:
  python-check-style:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - "4566-4599:4566-4599"
        environment:
          - SERVICES=s3
          - DEBUG=1
        volumes:
          - ./credentials:/root/.aws

    steps:
      - name: Git clone repo
        uses: actions/checkout@v1

      - name: Set up Docker
        uses: actions/setup-python@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Start LocalStack
        run: |
          docker run -d --name localstack --network host localstack/localstack

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Python Check Style
        run: |
          pip install pycodestyle
          pycodestyle .

      - name: Run Tests
        run: |
          pytest
