name: Vano Tasks
on:
  push:
    branches:
      - main

jobs:
  python-check-style:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - "4566-4599:4566-4599"
        environment:
          - SERVICES=s3
          - DEBUG=1
        volumes:
          - ./credentials:/root/.aws

    steps:
      - name: Git clone repo
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.0'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Python Check Style
        run: |
          pip install pycodestyle
          pycodestyle .

      - name: Run Tests
        run: pytest
