name: Vano Tasks
on:
  push:
    branches:
      - main

jobs:
  python-check-style:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@v1

      - name: Set version python python
        uses: actions/setup-python@1
        with:
          python-version: '3.11.0'
      - name: Install dependencies python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Python Check Style
        run: |
          pip install pycodestyle
          pycodestyle .
      - name: Run Tests
        run: pytest