name: Vano Tasks
on:
  push:
    branches:
      - main

jobs:
  python-check-style:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@v1

      - name: Set up Python
        run: |
          sudo apt update
          sudo apt install python3.11

      - name: Install dependencies python
        run: |
          python3.11 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Python Check Style
        run: |
          pip install pycodestyle
          pycodestyle .
      - name: Run Tests
        run: pytest
